### PR TITLE
Website overhaul

### PR DESCRIPTION
**Pull request by DefinitelyInconspicous**
Hi - I wanted to improve on the website as it looked a little bland, so Here's my initial commit :) Currently It's just the readme, but I styled it a bit.

### CODE REVIEW

**Comment by Bee4Queer** [comment]
Cool! I can't take a look at it right now, but when I get home I will!

**Comment by Bee4Queer** [comment]
Oh WOW! this looks sick, thanks so much! one nitpick tho(which was also on the old site probably): can you change the github link to link to this repo instead of the emperor numerius one? other than that, it looks good to me!

**Comment by DefinitelyInconspicous** [comment]
Alright, I changed some of the links to update them :)

**Comment by Bee4Queer** [comment]
Looks good! Merging now.

**Pull request merged**
